# -*- coding: utf-8 -*-
"""metrics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cr8bYYHsGueKWYHw16p-x-R19jjxdihd
"""

import numpy as np

revenue = np.array([[100,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

profit = revenue - expenses
profit

price_per_unit=([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

price_per_unit*units

"""**Numpy Broadcasting ⬆**"""

np.dot(price_per_unit,units)

"""**Sales Amount in year **"""

revenue_per_year = ([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
usDollar = 83

BS = revenue_per_year*usDollar
np.dot(revenue_per_year,usDollar)